### ISSUE TITLE
Plug Auction Contract into FE and Update UI

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-frontend#111]
Part 1 (Update Listing Process)

https://testnet.fraktal.io/list-nft

There are now 2 listing types: Fixed Price and Auction

To solve for this. Update the List NFT Screen as follows:
Add a Dropdown or Tabs for Choose Listing Type directly under "List your Fraktion NFT for sale"
1) Fixed Price
2) Auction

Then only thing that changes underneath for the input boxes is if Auction is selected instead of Total Price, it is Reserve Price.
<img width="615" alt="Screen Shot 2021-12-13 at 10 22 50" src="https://user-images.githubusercontent.com/43958441/145785557-d2edac02-9695-4b65-9b25-73f81f7c49ac.png">

Part 2) Update Marketplace Page

Add a Filter Dropdown Menu next to sort that has the following options:
1) All Listings
2) Fixed Price
3) Auctions

Part 3) Update Individual NFT Blocks
-Keep % available the same
-Instead of Total Price on bottom right, have a countdown timer with how much time left (starting at 10 days: hours: Min) -> could also go down to seconds if that is better UX.

Part 4) Update NFT Listing Details Page
-Available change to "For Sale"
-Price change to "Reserve Price" and remove 'per fraktion' text underneath
-Change Buy Fraktions block to "Contribute ETH", placeholder value from Fraktions to ETH, Buy Button to "Contribute"

Part 5) Claiming (excess ETH + Fraktions) after auction ends
These can probably be added on my NFTs page https://testnet.fraktal.io/my-nfts either as NFT Blocks or following how marketplace profit works.
-Need button to claim any leftover ETH, or if reserve price not met.
-Need button to claim Fraktions awarded.

**Comment by raouf-Bouky** [comment]
is it open ?
