### ISSUE TITLE
Buy-Out & Redeem for Finished Auctions

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-frontend#131]
**Background:**
Once an NFT is fractionalised, there are 2 ways to retrieve the native NFT.

1. Own 100% of fraktions (and burn them to retrieve native)
2. Offer a buy-out in ETH. Where holders of fraktions vote to accept/reject, and if approved they exchange fraktions for their share of the ETH.

This can be seen on fixed price auction listings in the Fraktal NFT buy-out section: https://fraktal-dapp-git-fork-nottotis-main-fraktal.vercel.app/nft/0x2484381d427d40c41b6ba569b4627d506c0ad7ae/details 

And in the Your Ownership left side column under NFT image (if you own 100%)

**Issue:** 
On Auction listings these 2 features on not available

**Desired**
Add the same Buy-out and DeFrak blocks as on fixed-price listings to auction listings.

**Comment by nottotis** [comment]
Resolved on below commit
https://github.com/FraktalNFT/dapp-frontend/pull/130/commits/0afcbb68f6996aa3a7d0a71cc6c3aa60e58ff044
