### ISSUE TITLE
Withdrawing NFT

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-frontend#217]
un-importing an NFT from fraktal to retrieve the native is not displaying in UI, even though txs appear to go through.

(rarible 721, os 721, os 155)
Needs to call approve in factory contract
Then call claim NFT function in market contract

**Comment by naftalimurgor** [comment]
Hi @cryptnotiq 

I noticed you closed #47 signalling the feature is no longer needed?

**Comment by AlexSnipes** [comment]
https://github.com/FraktalNFT/dapp-frontend/pull/262
