### ISSUE TITLE
Fix Design

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/dapp-frontend#233]
<img width="646" alt="Screen Shot 2022-03-02 at 17 15 14" src="https://user-images.githubusercontent.com/43958441/156402086-cde371d0-e9a3-4ca4-ae29-3088c7903eb5.png">

**Comment by naftalimurgor** [comment]
Hello @cryptnotiq 
I can take on this as it is doable. You may create a Gitcoin ticket if possible as I work on it.

Thanks
